const { blackA, green, grass, mauve } = require("@radix-ui/colors")
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,vue}"],
    daisyui: {
        themes: [
            "customblack",
            "light",
            "lofi",
            "cupcake",
            "corporate",
            "retro",
            "valentine",
            "garden",
            "aqua",
            "pastel",
            "wireframe",
            "winter",
            "cyberpunk",
            "bumblebee",
            "emerald",
            "fantasy",
            "cmyk",
            "autumn",
            "acid",
            "lemonade",
            "dark",
            "synthwave",
            "halloween",
            "forest",
            "black",
            "luxury",
            "dracula",
            "business",
            "night",
            "coffee",
            {
                forest: {
                    ...require("daisyui/src/theming/themes")["[data-theme=forest]"],
                    "base-content": "#f3f3f3",
                    "base-100": "#111",
                },
            },
            {
                synthwave: {
                    ...require("daisyui/src/theming/themes")["[data-theme=synthwave]"],
                    "base-100": "#2d1b69",
                    primary: "#ff2975",
                    secondary: "#ff901f",
                    "base-content": "#31f9fd",
                    // "base-300": "#0a0718"
                },
            },
            {
                coffee: {
                    ...require("daisyui/src/theming/themes")["[data-theme=coffee]"],
                    "base-200": "#1b131a",
                    "base-300": "#150f14",
                },
            },
            {
                night: {
                    ...require("daisyui/src/theming/themes")["[data-theme=night]"],
                    "base-200": "#0b1321",
                    "base-300": "#080f1a",
                    "base-content": "#b3c5ef",
                    // "primary": "#ff2975",
                    // "secondary": "#ff901f",
                    // "base-content": "#31f9fd"
                },
            },
            {
                curses: {
                    "color-scheme": "dark",
                    primary: "#FC6471",
                    // "primary-content": "#000000",
                    secondary: "#55D6BE",
                    accent: "#E5625E",
                    "base-content": "#34f09f",
                    "base-100": "#1C1F33",
                    // "base-200": "#d41344",
                    "base-300": "#151625",
                    // neutral: "#272626",
                    // "neutral-focus": "#343232",
                    info: "#0000ff",
                    success: "#008000",
                    warning: "#ffff00",
                    error: "#ff0000",
                    "--rounded-box": ".8rem",
                    "--rounded-btn": "0.5rem",
                    "--rounded-badge": "0",
                    "--animation-btn": "0",
                    "--animation-input": "0.5rem",
                    "--btn-text-case": "lowercase",
                    "--btn-focus-scale": "1",
                    "--tab-radius": "0",
                },
                staffy: {
                    "color-scheme": "dark",
                    primary: "#8741d6",
                    secondary: "#8741d6",
                    accent: "#00eb5e",
                    "base-content": "#f4e32a",
                    "base-100": "#333333",
                    "base-200": "#232323",
                    "base-300": "#212121",
                    neutral: "#272626",
                    "neutral-focus": "#343232",
                    info: "#0000ff",
                    success: "#008000",
                    warning: "#ffff00",
                    error: "#ff0000",
                    "--rounded-box": "0.8rem",
                    "--rounded-btn": "0.5rem",
                    "--rounded-badge": "0.5rem",
                    "--animation-btn": "0",
                    "--animation-input": "0.5rem",
                    "--btn-text-case": "lowercase",
                    "--btn-focus-scale": "1",
                    "--tab-radius": "0",
                },
                matrix: {
                    "color-scheme": "dark",
                    primary: "#80ce87",
                    secondary: "#204829",
                    accent: "#00eb5e",
                    "base-content": "#22b455",
                    "base-100": "#090909",
                    // "base-200": "#070707",
                    // "base-300": "#020202",
                    neutral: "#272626",
                    "neutral-focus": "#343232",
                    info: "#0000ff",
                    success: "#008000",
                    warning: "#ffff00",
                    error: "#ff0000",
                    "--rounded-box": "0rem",
                    "--rounded-btn": "0rem",
                    "--rounded-badge": "0",
                    "--animation-btn": "0",
                    "--animation-input": "0.5rem",
                    "--btn-text-case": "lowercase",
                    "--btn-focus-scale": "1",
                    "--tab-radius": "0",
                },
            },
        ],
    },
    theme: {
        extend: {
            transitionProperty: {
                spacing: "margin, padding",
            },
            colors: {
                ...blackA,
                ...green,
                ...grass,
                ...mauve,
            },
            keyframes: {
                slideDownAndFade: {
                    from: { opacity: 0, transform: "translateY(-2px)" },
                    to: { opacity: 1, transform: "translateY(0)" },
                },
                slideLeftAndFade: {
                    from: { opacity: 0, transform: "translateX(2px)" },
                    to: { opacity: 1, transform: "translateX(0)" },
                },
                slideUpAndFade: {
                    from: { opacity: 0, transform: "translateY(2px)" },
                    to: { opacity: 1, transform: "translateY(0)" },
                },
                slideRightAndFade: {
                    from: { opacity: 0, transform: "translateX(-2px)" },
                    to: { opacity: 1, transform: "translateX(0)" },
                },
                slideUp: {
                    from: { height: "var(--radix-collapsible-content-height)" },
                    to: { height: 0 },
                },
                slideDown: {
                    from: { height: 0 },
                    to: { height: "var(--radix-collapsible-content-height)" },
                },
                overlayShow: {
                    from: { opacity: 0 },
                    to: { opacity: 1 },
                },
                contentShow: {
                    from: { opacity: 0, transform: "translate(-50%, -48%) scale(0.96)" },
                    to: { opacity: 1, transform: "translate(-50%, -50%) scale(1)" },
                },
                shake: {
                    " 0%": { transform: "translate(0, 0)" },
                    "10%, 30%, 50%, 70%, 90%": { transform: "translate(-5px, 0)" },
                    "20%, 40%, 60%, 80%": { transform: "translate(5px, 0)" },
                    "100%": { transform: "translate(0, 0)" },
                },
            },
            animation: {
                slideDownAndFade: "slideDownAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)",
                slideLeftAndFade: "slideLeftAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)",
                slideUpAndFade: "slideUpAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)",
                slideRightAndFade: "slideRightAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)",
                slideUp: "slideUp 0.3s cubic-bezier(0.87, 0, 0.13, 1)",
                slideDown: "slideDown 0.3s cubic-bezier(0.87, 0, 0.13, 1)",
                overlayShow: "overlayShow 150ms cubic-bezier(0.16, 1, 0.3, 1)",
                contentShow: "contentShow 150ms cubic-bezier(0.16, 1, 0.3, 1)",
                shake: "shake 0.4s",
            },
        },
    },
    plugins: [require("daisyui")],
}
