/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayButton: typeof import('./components/AudioPlayButton.vue')['default']
    CheckAnimationButton: typeof import('./components/CheckAnimationButton.vue')['default']
    ContextMenu: typeof import('./components/contextmenu/ContextMenu.vue')['default']
    ContextMenuContent: typeof import('radix-vue')['ContextMenuContent']
    ContextMenuItem: typeof import('radix-vue')['ContextMenuItem']
    ContextMenuPortal: typeof import('radix-vue')['ContextMenuPortal']
    ContextMenuRoot: typeof import('radix-vue')['ContextMenuRoot']
    ContextMenuTrigger: typeof import('radix-vue')['ContextMenuTrigger']
    Counter: typeof import('./components/Counter.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    EmojiSelect: typeof import('./components/EmojiSelect.vue')['default']
    GQAutoPage: typeof import('./components/GQAutoPage.vue')['default']
    GQQuery: typeof import('./components/GQQuery.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    LocalQQ: typeof import('./components/LocalQQ.vue')['default']
    Popover: typeof import('./components/Popover.vue')['default']
    PopoverArrow: typeof import('radix-vue')['PopoverArrow']
    PopoverClose: typeof import('radix-vue')['PopoverClose']
    PopoverContent: typeof import('radix-vue')['PopoverContent']
    PopoverPortal: typeof import('radix-vue')['PopoverPortal']
    PopoverRoot: typeof import('radix-vue')['PopoverRoot']
    PopoverTrigger: typeof import('radix-vue')['PopoverTrigger']
    QQAvatar: typeof import('./components/QQAvatar.vue')['default']
    ResizeableWindow: typeof import('./components/ResizeableWindow.vue')['default']
    RichInput: typeof import('./components/RichInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./components/ScrollArea.vue')['default']
    ScrollAreaRoot: typeof import('radix-vue')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('radix-vue')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('radix-vue')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('radix-vue')['ScrollAreaViewport']
    Select: typeof import('./components/select/Select.vue')['default']
    SelectItem: typeof import('./components/select/SelectItem.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SidebarButton: typeof import('./components/SidebarButton.vue')['default']
    StatisticsProgress: typeof import('./components/StatisticsProgress.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
    UserItem: typeof import('./components/UserItem.vue')['default']
  }
}
